src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LieuRepository::class)]
class Lieu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_nom = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_capacite = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_adr_rue = null;

    #[ORM\OneToMany(mappedBy: 'lieu', targetEntity: Manifestation::class)]
    private Collection $manifestations;

    #[ORM\Column(length: 1000)]
    private ?string $affiche = null;

    public function __construct()
    {
        $this->manifestations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLieuNom(): ?string
    {
        return $this->lieu_nom;
    }

    public function setLieuNom(string $lieu_nom): self
    {
        $this->lieu_nom = $lieu_nom;

        return $this;
    }

    public function getLieuCapacite(): ?string
    {
        return $this->lieu_capacite;
    }

    public function setLieuCapacite(string $lieu_capacite): self
    {
        $this->lieu_capacite = $lieu_capacite;

        return $this;
    }

    public function getLieuAdrRue(): ?string
    {
        return $this->lieu_adr_rue;
    }

    public function setLieuAdrRue(string $lieu_adr_rue): self
    {
        $this->lieu_adr_rue = $lieu_adr_rue;

        return $this;
    }

    /**
     * @return Collection<int, Manifestation>
     */
    public function getManifestations(): Collection
    {
        return $this->manifestations;
    }

    public function addManifestation(Manifestation $manifestation): self
    {
        if (!$this->manifestations->contains($manifestation)) {
            $this->manifestations->add($manifestation);
            $manifestation->setLieu($this);
        }

        return $this;
    }

    public function removeManifestation(Manifestation $manifestation): self
    {
        if ($this->manifestations->removeElement($manifestation)) {
            // set the owning side to null (unless already changed)
            if ($manifestation->getLieu() === $this) {
                $manifestation->setLieu(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->lieu_nom;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }
}

src/Controller/SalleController.php
<?php

namespace App\Controller;

use App\Repository\LieuRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SalleController extends AbstractController
{
    #[Route('/salle', name: 'app_salle')]
    public function afficherSalle(LieuRepository $lieuRepository): Response
    {
        $lieux = $lieuRepository->findAll();
        return $this->render('salle/index.html.twig', [
            'Lieux' => $lieux,
        ]);
    }
}

templates/salle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Salles{% endblock %}

{% block body %}




        <div class="Salle">

    {% for Lieu in Lieux %}



            <div class="encadreSalle">

                <div class="afficheSalle">
                    <div class="carteSalle">

                        <img src="{{ asset("image_sae301/#{Lieu.affiche}") }}"alt="{{ Lieu.lieuNom }}">



                    </div>
                    <div class="carteBasSalle">
                        <p class="p1"> {{ Lieu.lieuNom }}</p>
                        <p class="p2"> <i class="fa-solid fa-location-dot"></i>{{ Lieu.lieuAdrRue }}</p>

                        <p class="p3"> <i class="fa-solid fa-users-viewfinder"></i></i>  {{ Lieu.lieuCapacite }}</p>
                        <div class="1star"><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i></div>


                    </div>
                </div>








            </div>
        </div>
    {% endfor %}
        </div>







        <style>
            @import url('https://fonts.googleapis.com/css2?family=Nerko+One&display=swap');
            @import url('https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap');


        </style>


{% endblock %}